# version: 2.1

# orbs:
#   unity: game-ci/unity@1.7.0

# jobs:
#   build-android:
#     executor:
#       name: unity/ubuntu
#       editor_version: 2022.3.20f1
#       resource_class: medium
#       # target_platform: android
#     steps:
#       - checkout
#       # - unity/prepare-env
#       - unity/build:
#           build-target: Android
#           # compress: false
#           # store-artifacts: false
#           # persist-to-workspace: true


# workflows:
#   build-unity-android:
#     jobs:
#       - build-android:
#           # context: unity


version: 2.1

orbs:
  unity: game-ci/unity@1.7.0

workflows:
  build-unity-project:  
    jobs:
    - unity/create-activation-file:
          name: "create-activation-file"
    - unity/build:
          name: "build-android"
          step-name: "Build Android"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "android"
            editor_version: 2022.3.20f1
            resource_class: "medium"
          project-path: "src"
          build-target: "Android"
          compress: true
          context: unity
      #  upload-artifacts:      
      #   requires: 
      #     - build-android

#   build-android:
#     executor:
#       name: unity/ubuntu
#     steps:
#       - checkout
#       - unity/build:

# workflows:
#   build-unity-android:
#     jobs:
#       - build-android