# version: 2.1

# orbs:
#   unity: game-ci/unity@1.7.0

# jobs:
#   build-android:
#     executor:
#       name: unity/ubuntu
#       editor_version: 2022.3.20f1
#       resource_class: medium
#       # target_platform: android
#     steps:
#       - checkout
#       # - unity/prepare-env
#       - unity/build:
#           build-target: Android
#           # compress: false
#           # store-artifacts: false
#           # persist-to-workspace: true


# workflows:
#   build-unity-android:
#     jobs:
#       - build-android:
#           # context: unity


version: 2.1

orbs:
  unity: game-ci/unity@1.7.0


workflows:
  build-unity-project:  
    jobs:
    - unity/create-activation-file:
          name: "create-activation-file"

#   build-android:
#     executor:
#       name: unity/ubuntu
#       editor_version: 2022.3.20f1
#       resource_class: medium
#       target_platform: android
#     steps:
#       - checkout
#       - unity/build:
#           unity-license-var-name: "UNITY_ENCODED_LICENSE"
#           unity-username-var-name: "UNITY_USERNAME"
#           unity-password-var-name: "UNITY_PASSWORD"
#           project-path: .
#           build-target: Android

# workflows:
#   build-unity-android:
#     jobs:
#       - build-android